{% set name = "fgt" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gadomski/fgt/archive/v{{ version }}.tar.gz
  sha256: 677213957dff59d6f546855663670fa7991eb69fbe9caa9312c1296c2360fcb1
  patches:
    - fgt.patch

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - eigen
    - openmpi  # [not win]
  run:
    - eigen
    - openmpi  # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libfgt.a  # [not win]
    - if not exist %LIBRARY_LIB%\\fgt.lib exit 1  # [win]

about:
  home: https://github.com/gadomski/fgt/
  license: LGPL-2.0-or-later
  license_file: LICENSE.txt
  summary: C++ library for fast Gauss transforms.
  description: |
    C++ library for fast Gauss transforms
  doc_url: https://github.com/gadomski/fgt/
  dev_url: https://github.com/gadomski/fgt/

extra:
  recipe-maintainers:
    - hobu
    - chambbj
    - gadomski
