{% set name = "fgt" %}
{% set version = "0.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gadomski/fgt/archive/v{{ version }}.tar.gz
  sha256: 3f11165ae3bb6c349b1fb8971bb4bdeee2c58ca68184e8c603f1964a67282e3b

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - eigen
    - make  # [unix]
    - openmpi  # [unix]
  run:
    - eigen
    - openmpi  # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libfgt.dylib  # [osx]
    - test -f ${PREFIX}/lib/libfgt.so  # [linux]
    - if not exist %LIBRARY_LIB%\\fgt.lib exit 1  # [win]

about:
  home: https://github.com/gadomski/fgt/
  license: LGPL-2.0-or-later
  license_file: LICENSE.txt
  summary: C++ library for fast Gauss transforms.
  description: |
    C++ library for fast Gauss transforms
  doc_url: https://github.com/gadomski/fgt/
  dev_url: https://github.com/gadomski/fgt/

extra:
  recipe-maintainers:
    - hobu
    - chambbj
    - gadomski
